version: '3.8'
services:
  dev-db:
    image: postgres:15.0-alpine
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=cashier
    networks:
      - cashierapp
  test-db:
    image: postgres:15.0-alpine
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=cashier
    networks:
      - cashierapp
networks:
  cashierapp:
