name: Node CD

on:
  push:
    branches: ['development']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Deploy using ssh
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            cd ~/cashier-app
            git pull origin development
            git status
            pnpm install
            pnpm build
            pm2 restart cashier-app
