name: Svelte Vitest

on: [push, pull_request]
jobs:
  vitest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: setup node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install pnpm
        run: npm install -g pnpm
      - name: svelte check code
        run: pnpm check
      - name: unit test
        run: pnpm test:unit
